### ISSUE TITLE
Anlaytics Usage' is not submitted because of special charecters like '&' and 'comma' in exp_name

### ISSUE THREAD

**Issue by sravanthimodepu** [vlabs-on-openedx/open-edx-analog-cmos-vlsi-circuit-design-iiith#1]
Analytics Usage' is not submitted because of special characters like '&', 'comma', ':' in exp_name.

**Comment by mrudhvika940** [comment]
After updating the corrected exp_id, analytics usage is  submitted.

**Comment by sravanthimodepu** [comment]
Closing the issue.
